os: Visual Studio 2017
clone_depth: 1
deploy: off

assembly_info:
    assembly_informational_version: "{version} - CI (AppVeyor, branch: {branch})"

configuration:
    - Debug
    - Release

init:
  - git config --global core.autocrlf true

before_build:
  - dotnet restore
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory packages
  - nuget install Codecov -Version 1.0.3 -OutputDirectory packages

build_script:
  - dotnet build -c %CONFIGURATION% "Decorator\Decorator.csproj"
  
test_script:
    - ps: |
        if ($env:CONFIGURATION -eq 'Release')
        {
          dotnet test Decorator.Tests\ /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          
          packages\Codecov.1.0.3\tools\codecov.exe -f "Decorator.Tests\coverage.opencover.xml"
        }

artifacts:
 - path: 'Decorator\bin\%CONFIGURATION%\*.nupkg'
   name: Decorator.zip
   